export const TOGGLE_ERROR = 'TOGGLE_ERROR';
export const SHOW_ERROR = 'SHOW_ERROR';
export const RESET_ERROR = 'RESET_ERROR';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const TOGGLE_TOAST = 'TOGGLE_TOAST';
export const TOGGLE_SNACKBAR = 'TOGGLE_SNACKBAR';
export const FETCH_LOGIN = 'FETCH_LOGIN';
export const FETCH_LOGOUT = 'FETCH_LOGOUT';

export const MUTATE_BETA_ENTRY = 'MUTATE_BETA_ENTRY';

export const QUERY_BETA_ENTRIES = 'QUERY_BETA_ENTRIES';
